# Generated by Django 5.0.7 on 2024-08-13 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionFigure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Action Figures', 'Action Figures')], max_length=255)),
                ('subcategory', models.CharField(blank=True, choices=[('Superheroes', 'Superheroes'), ('Movie Characters', 'Movie Characters'), ('Historical Figures', 'Historical Figures')], max_length=255, null=True)),
                ('company', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.URLField()),
            ],
        ),
    ]
